apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-ms

  template:
    metadata:
      labels:
        app: user-ms

    spec:
      containers:
        - name: user-ms

          image: gourav60/user-ms:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-service:3306/hms_db

            - name: DB_USERNAME
              value: hms

            - name: DB_PASSWORD
              value: root

            - name: GATEWAY_SERVICE_URL
              value: http://gateway-service:9000

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/

---

apiVersion: v1
kind: Service
metadata:
  name: user-ms-service

spec:
  selector:
    app: user-ms

  ports:
    - port: 8080
      targetPort: 8080

  type: ClusterIP