pipeline {

    agent any

    environment {

        DOCKERHUB = "gourav60"

        TAG = "${BUILD_NUMBER}"
    }

    stages {

        // =========================================
        // CLONE CODE
        // =========================================

        stage('Clone Code') {

            steps {

                git branch: 'main',
                        url: 'https://github.com/gmahor/hospital-management-system.git'
            }
        }

        // =========================================
        // DETECT CHANGES
        // =========================================

        stage('Detect Changes') {

            steps {

                script {

                    if (env.BUILD_NUMBER == "1") {

                        echo "First Build Detected"

                        env.CHANGED_FILES = """
                        hms-backend/eureka/
                        hms-backend/gatewayMS/
                        hms-backend/userMS/
                        hms-backend/ProfileMS/
                        hms-backend/appointment/
                        """

                    } else {

                        env.CHANGED_FILES = sh(
                                script: "git diff --name-only HEAD~1 HEAD",
                                returnStdout: true
                        ).trim()
                    }

                    echo "Changed Files:"
                    echo env.CHANGED_FILES
                }
            }
        }

        // =========================================
        // DOCKER LOGIN
        // =========================================

        stage('Docker Login') {

            steps {

                withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        // =========================================
        // EUREKA
        // =========================================

        stage('Build Eureka') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/eureka/")
                }
            }

            steps {

                dir('hms-backend/eureka') {

                    sh 'mvn clean package -DskipTests'

                    sh """
                    docker build \
                    -t ${DOCKERHUB}/eureka:${TAG} \
                    -t ${DOCKERHUB}/eureka:latest .
                    """
                }
            }
        }

        stage('Push Eureka') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/eureka/")
                }
            }

            steps {

                sh "docker push ${DOCKERHUB}/eureka:${TAG}"

                sh "docker push ${DOCKERHUB}/eureka:latest"
            }
        }

        stage('Deploy Eureka') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/eureka/")
                }
            }

            steps {

                sh """
                kubectl set image deployment/eureka-deployment \
                eureka=${DOCKERHUB}/eureka:${TAG}
                """

                sh 'kubectl rollout status deployment/eureka-deployment'
            }
        }

        // =========================================
        // GATEWAY
        // =========================================

        stage('Build Gateway') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/gatewayMS/")
                }
            }

            steps {

                dir('hms-backend/gatewayMS') {

                    sh 'mvn clean package -DskipTests'

                    sh """
                    docker build \
                    -t ${DOCKERHUB}/gateway:${TAG} \
                    -t ${DOCKERHUB}/gateway:latest .
                    """
                }
            }
        }

        stage('Push Gateway') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/gatewayMS/")
                }
            }

            steps {

                sh "docker push ${DOCKERHUB}/gateway:${TAG}"

                sh "docker push ${DOCKERHUB}/gateway:latest"
            }
        }

        stage('Deploy Gateway') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/gatewayMS/")
                }
            }

            steps {

                sh """
                kubectl set image deployment/gateway-deployment \
                gateway=${DOCKERHUB}/gateway:${TAG}
                """

                sh 'kubectl rollout status deployment/gateway-deployment'
            }
        }

        // =========================================
        // USER SERVICE
        // =========================================

        stage('Build UserMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/userMS/")
                }
            }

            steps {

                dir('hms-backend/userMS') {

                    sh 'mvn clean package -DskipTests'

                    sh """
                    docker build \
                    -t ${DOCKERHUB}/user-ms:${TAG} \
                    -t ${DOCKERHUB}/user-ms:latest .
                    """
                }
            }
        }

        stage('Push UserMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/userMS/")
                }
            }

            steps {

                sh "docker push ${DOCKERHUB}/user-ms:${TAG}"

                sh "docker push ${DOCKERHUB}/user-ms:latest"
            }
        }

        stage('Deploy UserMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/userMS/")
                }
            }

            steps {

                sh """
                kubectl set image deployment/user-ms-deployment \
                user-ms=${DOCKERHUB}/user-ms:${TAG}
                """

                sh 'kubectl rollout status deployment/user-ms-deployment'
            }
        }

        // =========================================
        // PROFILE SERVICE
        // =========================================

        stage('Build ProfileMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/ProfileMS/")
                }
            }

            steps {

                dir('hms-backend/ProfileMS') {

                    sh 'mvn clean package -DskipTests'

                    sh """
                    docker build \
                    -t ${DOCKERHUB}/profile-ms:${TAG} \
                    -t ${DOCKERHUB}/profile-ms:latest .
                    """
                }
            }
        }

        stage('Push ProfileMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/ProfileMS/")
                }
            }

            steps {

                sh "docker push ${DOCKERHUB}/profile-ms:${TAG}"

                sh "docker push ${DOCKERHUB}/profile-ms:latest"
            }
        }

        stage('Deploy ProfileMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/ProfileMS/")
                }
            }

            steps {

                sh """
                kubectl set image deployment/profile-ms-deployment \
                profile-ms=${DOCKERHUB}/profile-ms:${TAG}
                """

                sh 'kubectl rollout status deployment/profile-ms-deployment'
            }
        }

        // =========================================
        // APPOINTMENT SERVICE
        // =========================================

        stage('Build AppointmentMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/appointment/")
                }
            }

            steps {

                dir('hms-backend/appointment') {

                    sh 'mvn clean package -DskipTests'

                    sh """
                    docker build \
                    -t ${DOCKERHUB}/appointment-ms:${TAG} \
                    -t ${DOCKERHUB}/appointment-ms:latest .
                    """
                }
            }
        }

        stage('Push AppointmentMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/appointment/")
                }
            }

            steps {

                sh "docker push ${DOCKERHUB}/appointment-ms:${TAG}"

                sh "docker push ${DOCKERHUB}/appointment-ms:latest"
            }
        }

        stage('Deploy AppointmentMS') {

            when {
                expression {
                    return env.CHANGED_FILES.contains("hms-backend/appointment/")
                }
            }

            steps {

                sh """
                kubectl set image deployment/appointment-ms-deployment \
                appointment-ms=${DOCKERHUB}/appointment-ms:${TAG}
                """

                sh 'kubectl rollout status deployment/appointment-ms-deployment'
            }
        }

        // =========================================
        // VERIFY
        // =========================================

        stage('Verify') {

            steps {

                sh 'kubectl get pods'

                sh 'kubectl get svc'
            }
        }
    }
}