server:
  port: 8082

spring:
  application:
    name: appointment

  datasource:
    url: jdbc:postgresql://localhost:5432/hms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata


  graphql:
    graphiql:
      enabled: true
      path: /graphql